config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages

  post 'messages/prescription', to: 'messages#prescription', as: 'prescription'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :inbox
  belongs_to :outbox

end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
require 'will_paginate/array'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success
end

app/controllers/messages_controller.rb
 class MessagesController < ApplicationController
  
  def show
    @message = Message.find(params[:id])
    session[:outbox] = @message.outbox.id
    session[:inbox] = @message.inbox.id
    @message.read = true
    @message.save
  end

  def index
  	@messages = User.current.inbox.messages.reverse #Use reverse method for newest messages uptop
    @messages = @messages.paginate(page: params[:page],per_page: 10) #will_paginate gem used here
  end

  def new
    @message = Message.new
  end

  def prescription
    @current_user = User.current
    @default_admin = User.default_admin
    @lost_presc_message = "I have lost my prescription!/n" + @current_user.full_name
    @message = Message.create!(body: @lost_presc_message, outbox: @current_user.outbox, inbox: @default_admin.inbox )
    
    if PaymentProviderFactory.provider.debit_card(@current_user)
      @payment = Payment.create!(@current_user)
      flash[:success] = "Order is successfull"
      redirect_to 
    else
      render root
      flash[:alert] = "Transaction failed. Please try again"
    end
    
  end

  def create
    @outbox = Outbox.find(session[:outbox])
    @inbox = Inbox.find(session[:inbox])
    @message = Message.create!(body: params[:message][:body],outbox: @outbox, inbox: @inbox)

	if 1.week.ago < @message.created_at
    redirect_to '/'
    flash[:success] = "Message successfully sent"
	else
		@message.inbox = User.default_admin.inbox
		@message.save
    flash[:success] = "Message sent to admin"
	end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/ce9bd5c46d.js" crossorigin="anonymous"></script>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0"><%= User.current.first_name + " " + User.current.last_name + "'s Inbox" %></h6>
  <% @messages.each do |message| %>
    <%= link_to message do %>
      <div class="media <%= message.read ? 'text-muted' : 'text' %> pt-3"><!-- Muted if read -->
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %></strong>
          <%= message.body.truncate(100) %>
        </p>
      </div>
    <% end %>
  <% end %>
<%= will_paginate @messages %>
  <small class="d-block text-right mt-3">
    <a href="#">All updates</a>
  </small>
</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <%= form_for @message, :url => {:action => "create"} do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3 %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <%= link_to "Reply", new_message_path, class: "btn btn-primary" %>
    <%= link_to "I've lost my prescription",prescription_path,method: :post, class: "btn btn-primary" %>
  </div>
</div>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          <i style="font-size: 1.75rem" class="fas fa-inbox"></i>
          <span class='badge badge-warning' id='lblCartCount'><%= User.current.inbox.messages.where(read:false).count %></span>
        <% end  %>
      </li>
    </ul>
  </div>
</nav>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>